kind: role
version: v7
metadata:
  name: role-kube-access
spec:
  allow:
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
      - kind: namespace
        name: '{{external.team}}'
      - kind: pod
        namespace: '{{external.team}}'
        name: '*'
    kubernetes_groups:
      - '{{external.team}}'
  options:
    max_session_ttl: 8h0m0s
